server:  
  port: 8080 

spring.thymeleaf:
  cache: false
  mode: LEGACYHTML5
  encoding: UTF-8
  content-type: text/html

logging:
  level:
    org.springframework.web: INFO
    com.github.binarywang.demo.wechat: INFO

wechat:
  mp:
    appId: wxd3f024b0786b9a46
    secret: 7d5b94a14382453f9b8bd8e4c1256468
    token: albert1018
    aesKey: PdFZZgxL2bf1eZem6hlZRyjAlfGt7AY5PLZV8lNyKST
  admin:
    secret-key: 3j3J
    host-url: http://www.sviip.com
   
spring.datasource: 
  url: jdbc:mysql://122.112.197.187:23306/confinement_wechat
  username: root
  password: syadmin2589
  type: com.alibaba.druid.pool.DruidDataSource
  driver-class-name: com.mysql.jdbc.Driver
  initial-size: 5
  min-idle: 5
  max-idle: 100
  max-wait: 10000
  validation-query: SELECT 1

spring.jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.show_sql: true
spring.http.encoding.force: true