server:  
  port: 8080 
  
spring.thymeleaf.cache: false
spring.thymeleaf.mode: LEGACYHTML5
spring.thymeleaf.encoding: UTF-8
spring.thymeleaf.content-type: text/html

logging:
  level:
    org.springframework.web: DEBUG
    com.github.binarywang.demo.wechat: DEBUG

wechat:
  mp:
    appId: wxd3f024b0786b9a46
    secret: 7d5b94a14382453f9b8bd8e4c1256468
    token: albert1018
    aesKey: PdFZZgxL2bf1eZem6hlZRyjAlfGt7AY5PLZV8lNyKST
   